apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: gitlab
    repo: "https://charts.gitlab.io/"
    version: 6.11.0
    releaseName: gitlab
    namespace: gitlab
    valuesFile: values-gitlab.yaml

namespace: gitlab
